# Generated by Django 3.0.7 on 2020-06-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnanda', '0004_auto_20200607_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
