# Generated by Django 3.0.7 on 2020-06-07 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('keeya', '0002_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post_pics'),
            preserve_default=False,
        ),
    ]
